trusty-steps: &trusty-steps
  os: linux

xenial-steps: &xenial-steps
  os: linux
  dist: xenial
  
osx-steps: &osx-steps
  os: osx
  language: shell  # 'language: python' is not yet supported on Travis CI macOS

windows-steps: &windows-steps
  os: windows
  language: shell  # 'language: python' is not yet supported on Travis CI Windows

language: python
matrix:
  include:
    # Trusty Linux
    - name: "Python 2.7 on Trusty Linux"
      <<: *trusty-steps
      python: 2.7
    - name: "Python 3.5 on Trusty Linux"
      <<: *trusty-steps
      python: 3.5
    - name: "Python 3.6 on Trusty Linux"
      <<: *trusty-steps
      python: 3.6
    - name: "Python 3.7 on Trusty Linux"
      <<: *trusty-steps
      python: 3.7
    # Xenial Linux      
    - name: "Python 2.7 on Xenial Linux"
      <<: *xenial-steps
      python: 2.7
    - name: "Python 3.5 on Xenial Linux"
      <<: *xenial-steps
      python: 3.5
    - name: "Python 3.6 on Xenial Linux"
      <<: *xenial-steps
      python: 3.6
    - name: "Python 3.7 on Xenial Linux"
      <<: *xenial-steps
      python: 3.7
    # macOS
    - name: "Python 2.7 on macOS"
      <<: *osx-steps
      python: 2.7
    - name: "Python 3.5 on macOS"
      <<: *osx-steps
      python: 3.5
    - name: "Python 3.6 on macOS"
      <<: *osx-steps
      python: 3.6
    - name: "Python 3.7 on macOS"
      <<: *osx-steps
      python: 3.7
    # Trusty Linux
    - name: "Python 2.7 on Windows"
      <<: *windows-steps
      python: 2.7
    - name: "Python 3.5 on Windows"
      <<: *windows-steps
      python: 3.5
    - name: "Python 3.6 on Windows"
      <<: *windows-steps
      python: 3.6
    - name: "Python 3.7 on Windows"
      <<: *windows-steps
      python: 3.7
script:
  - pip --version || true
  - python --version || true
  - python2 --version || true
  - python3 --version || true
  - py --version || true
  - pip --version || true
