trusty-steps: &trusty-steps
  os: linux

xenial-steps: &xenial-steps
  os: linux
  dist: xenial
  
trusty-cpp-steps: &trusty-cpp-steps
  <<: *trusty-steps
  language: cpp

xenial-cpp-steps: &xenial-cpp-steps
  <<: *xenial-steps
  language: cpp

osx-steps: &osx-steps
  os: osx
  language: shell  # 'language: python' is not yet supported on Travis CI macOS

windows-steps: &windows-steps
  os: windows
  language: shell  # 'language: python' is not yet supported on Travis CI Windows

language: python
matrix:
  allow_failures:
    - name: "Python 3.7 on Trusty Linux"
    - name: "Python 3.7-dev on Trusty Linux cpp"
    - name: "Python 3.7-dev on Xenial Linux cpp"
  include:
    - name: "Python 3.7-dev on Xenial Linux cpp"
      <<: *xenial-cpp-steps
      before_install:
        - pyenv --version || true
        - pyenv update || true
        - pyenv upgrade || true
    # macOS =====================
    - name: "Python 2.7 on macOS"
      <<: *osx-steps
      python: 3.7
      before_install:
        - pyenv --version || true
        - pyenv update || true
        - pyenv upgrade || true

install: python -m pip install --upgrade pip
script:
  - python --version ; pip --version
  - pyenv --version ; pyenv --list || true
  #- which -a python || true
  #- which -a python2 || true
  #- which -a python3 || true
  #- which -a python3.4 || true
  #- which -a python3.5 || true
  #- python2.7 --version ; python2.7 -m pip --version || true
  #- python3.5 --version ; python3.5 -m pip --version || true
  #- python3.6 --version ; python3.6 -m pip --version || true
  #- python3.7 --version ; python3.7 -m pip --version || true
  #- py --version ; py -m pip --version || true
  #- pip --version ; true
