trusty-steps: &trusty-steps
  os: linux

xenial-steps: &xenial-steps
  os: linux
  dist: xenial
  
osx-steps: &osx-steps
  os: osx
  language: shell  # 'language: python' is not yet supported on Travis CI macOS

windows-steps: &windows-steps
  os: windows
  language: shell  # 'language: python' is not yet supported on Travis CI Windows

language: python
matrix:
  allow_failures:
    - name: "Python 3.7 on Trusty Linux"
  include:
    # Trusty Linux
    - name: "Python 2.7 on Trusty Linux"
      <<: *trusty-steps
      python: 2.7
    - name: "Python 3.5 on Trusty Linux"
      <<: *trusty-steps
      python: 3.5
    - name: "Python 3.6 on Trusty Linux"
      <<: *trusty-steps
      python: 3.6
    - name: "Python 3.7 on Trusty Linux"
      <<: *trusty-steps
      python: 3.7
    # Xenial Linux      
    - name: "Python 2.7 on Xenial Linux"
      <<: *xenial-steps
      python: 2.7
    - name: "Python 3.5 on Xenial Linux"
      <<: *xenial-steps
      python: 3.5
    - name: "Python 3.6 on Xenial Linux"
      <<: *xenial-steps
      python: 3.6
    - name: "Python 3.7 on Xenial Linux"
      <<: *xenial-steps
      python: 3.7
    # macOS
    - name: "Python 2.7 on macOS"
      <<: *osx-steps
      python: 2.7
    - name: "Python 3.5 on macOS"
      <<: *osx-steps
      python: 3.5
      before_install:
        - brew install --upgrade pyenv
        - pyenv install 3.5 # .5
    - name: "Python 3.6 on macOS"
      <<: *osx-steps
      python: 3.6
    - name: "Python 3.7 on macOS"
      <<: *osx-steps
      python: 3.7
      before_install:
       - brew install --upgrade pyenv
       - pyenv install 3.7
    # Trusty Linux
    - name: "Python 2.7 on Windows"
      <<: *windows-steps
      python: 2.7
      before_install: choco install python2
    - name: "Python 3.5 on Windows"
      <<: *windows-steps
      python: 3.5
      before_install: choco install python --version 3.5
    - name: "Python 3.6 on Windows"
      <<: *windows-steps
      python: 3.6
      before_install: choco install python --version 3.6
    - name: "Python 3.7 on Windows"
      <<: *windows-steps
      python: 3.7
      before_install: choco install python --version 3
script:
  - python --version ; pip --version || true
  - python2.7 --version ; python2.7 -m pip --version || true
  - python3.5 --version ; python3.5 -m pip --version || true
  - python3.6 --version ; python3.6 -m pip --version || true
  - python3.7 --version ; python3.7 -m pip --version || true
  - py --version ; py -m pip --version || true
  - pip --version ; true
