language: python
matrix:
  include:
    # Trusty Linux
    - name: "Python 2.7 on Trusty Linux"
      os: linux
      python: 2.7
    - name: "Python 3.5 on Trusty Linux"
      os: linux
      python: 3.5
    - name: "Python 3.6 on Trusty Linux"
      os: linux
      python: 3.6
    - name: "Python 3.7 on Trusty Linux"
      os: linux
      python: 3.7
    # Xenial Linux      
    - name: "Python 2.7 on Xenial Linux"
      os: linux
      dist: xenial
      python: 2.7
    - name: "Python 3.5 on Xenial Linux"
      os: linux
      dist: xenial
      python: 3.5
    - name: "Python 3.6 on Xenial Linux"
      os: linux
      dist: xenial
      python: 3.6
    - name: "Python 3.7 on Xenial Linux"
      os: linux
      dist: xenial
      python: 3.7
    # macOS
    - name: "Python 2.7 on macOS"
      os: osx
      python: 2.7
    - name: "Python 3.5 on macOS"
      os: osx
      python: 3.5
    - name: "Python 3.6 on macOS"
      os: osx
      python: 3.6
    - name: "Python 3.7 on macOS"
      os: osx
      python: 3.7
    # Trusty Linux
    - name: "Python 2.7 on Windows"
      os: windows
      python: 2.7
    - name: "Python 3.5 on Windows"
      os: windows
      python: 3.5
    - name: "Python 3.6 on Windows"
      os: windows
      python: 3.6
    - name: "Python 3.7 on Windows"
      os: windows
      python: 3.7
script:
  python --version || true
  python2 --version || true
  python3 --version || true
  py --version || true
  pip --version || true
